// <auto-generated />
using System;
using GameStore.api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.api.Data.migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20250128162356_SeedGenres")]
    partial class SeedGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GameStore.api.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GOTY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GOTY = false,
                            GenreId = 1,
                            Name = "Halo",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 2,
                            GOTY = false,
                            GenreId = 3,
                            Name = "The Witcher 3",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 3,
                            GOTY = false,
                            GenreId = 4,
                            Name = "The Sims 4",
                            Price = 29.99m,
                            ReleaseDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 4,
                            GOTY = false,
                            GenreId = 5,
                            Name = "Civilization VI",
                            Price = 49.99m,
                            ReleaseDate = new DateOnly(1, 1, 1)
                        });
                });

            modelBuilder.Entity("GameStore.api.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Strategy"
                        });
                });

            modelBuilder.Entity("GameStore.api.Entities.Game", b =>
                {
                    b.HasOne("GameStore.api.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
